In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('/Users/melodymassis/Documents/MIDS/yelp_business - yelp_business.csv')

In [5]:
df.head()

,business_id,name,neighborhood,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,categories
0,FYWN1wneV18bWNgQjJ2GNg,"""Dental by Design""",NaN,"""4855 E Warner Rd, Ste B9""",Ahwatukee,AZ,85044,33.330690,-111.978599,4.0,22,1,Dentists;General Dentistry;Health & Medical;Or...
1,He-G7vWjzVUysIKrfNbPUQ,"""Stephen Szabo Salon""",NaN,"""3101 Washington Rd""",McMurray,PA,15317,40.291685,-80.104900,3.0,11,1,Hair Stylists;Hair Salons;Men's Hair Salons;Bl...
2,KQPW8lFf1y5BT2MxiSZ3QA,"""Western Motor Vehicle""",NaN,"""6025 N 27th Ave, Ste 1""",Phoenix,AZ,85017,33.524903,-112.115310,1.5,18,1,Departments of Motor Vehicles;Public Services ...
3,8DShNS-LuFqpEWIp0HxijA,"""Sports Authority""",NaN,"""5000 Arizona Mills Cr, Ste 435""",Tempe,AZ,85282,33.383147,-111.964725,3.0,9,0,Sporting Goods;Shopping
4,PfOCPjBrlQAnz__NXj9h_w,"""Brick House Tavern + Tap""",NaN,"""581 Howe Ave""",Cuyahoga Falls,OH,44221,41.119535,-81.475690,3.5,116,1,American (New);Nightlife;Bars;Sandwiches;Ameri...

In [6]:
df.describe()

,latitude,longitude,stars,review_count,is_open
count,174566.000000,174566.000000,174567.000000,174567.000000,174567.000000
mean,38.627312,-92.679009,3.632196,30.137059,0.840376
std,5.389012,26.240079,1.003739,98.208174,0.366258
min,-36.086009,-142.466650,1.000000,3.000000,0.000000
25%,33.631550,-112.125879,3.000000,4.000000,1.000000
50%,36.144257,-89.410128,3.500000,8.000000,1.000000
75%,43.606181,-79.657609,4.500000,23.000000,1.000000
max,89.999314,115.086769,5.000000,7361.000000,1.000000

In [7]:
df.loc[:]

,business_id,name,neighborhood,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,categories
0,FYWN1wneV18bWNgQjJ2GNg,"""Dental by Design""",NaN,"""4855 E Warner Rd, Ste B9""",Ahwatukee,AZ,85044,33.330690,-111.978599,4.0,22,1,Dentists;General Dentistry;Health & Medical;Or...
1,He-G7vWjzVUysIKrfNbPUQ,"""Stephen Szabo Salon""",NaN,"""3101 Washington Rd""",McMurray,PA,15317,40.291685,-80.104900,3.0,11,1,Hair Stylists;Hair Salons;Men's Hair Salons;Bl...
2,KQPW8lFf1y5BT2MxiSZ3QA,"""Western Motor Vehicle""",NaN,"""6025 N 27th Ave, Ste 1""",Phoenix,AZ,85017,33.524903,-112.115310,1.5,18,1,Departments of Motor Vehicles;Public Services ...
3,8DShNS-LuFqpEWIp0HxijA,"""Sports Authority""",NaN,"""5000 Arizona Mills Cr, Ste 435""",Tempe,AZ,85282,33.383147,-111.964725,3.0,9,0,Sporting Goods;Shopping
4,PfOCPjBrlQAnz__NXj9h_w,"""Brick House Tavern + Tap""",NaN,"""581 Howe Ave""",Cuyahoga Falls,OH,44221,41.119535,-81.475690,3.5,116,1,American (New);Nightlife;Bars;Sandwiches;Ameri...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
174562,ALV5R8NkZ1KGOZeuZl3u0A,"""Whitby Toyota""",NaN,"""1025 Dundas Street W""",Whitby,ON,L1P 1Z1,43.873460,-78.968033,4.0,4,1,Car Dealers;Automotive
174563,gRGalHVu6BcaUDIAGVW_xQ,"""Village Auto Body""",NaN,"""3957 Brecksville Rd""",Richfield,OH,44286,41.243385,-81.636212,5.0,3,1,Body Shops;Automotive
174564,XXvZBIHoJBU5d6-a-oyMWQ,"""AAM""",NaN,"""1600 W Broadway Rd, Ste 200""",Tempe,AZ,85282,33.407914,-111.965098,1.5,19,1,Home Services;Property Management;Real Estate
174565,lNpPGgM96nPIYM1shxciHg,"""Bronze Beauty Spray Tanning""",NaN,"""300 Camp Horne Rd, Ste 250""",Pittsburgh,PA,15202,40.517724,-80.091466,5.0,14,1,Spray Tanning;Tanning;Beauty & Spas
174566,viKaP26BcHU6cLx8sf4gKg,"""Phoenix Pharmacy""",NaN,"""1701 East Thomas Rd, Ste 105""",Phoenix,AZ,85016,33.479861,-112.044689,5.0,4,1,Drugstores;Shopping;Health & Medical

In [23]:
df.value_counts('state')

state
AZ     52214
NV     33086
ON     30208
NC     12956
OH     12609
       ...
3          1
KY         1
MN         1
MT         1
ZET        1
Length: 67, dtype: int64

In [9]:
df.drop_duplicates()

,business_id,name,neighborhood,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,categories
0,FYWN1wneV18bWNgQjJ2GNg,"""Dental by Design""",NaN,"""4855 E Warner Rd, Ste B9""",Ahwatukee,AZ,85044,33.330690,-111.978599,4.0,22,1,Dentists;General Dentistry;Health & Medical;Or...
1,He-G7vWjzVUysIKrfNbPUQ,"""Stephen Szabo Salon""",NaN,"""3101 Washington Rd""",McMurray,PA,15317,40.291685,-80.104900,3.0,11,1,Hair Stylists;Hair Salons;Men's Hair Salons;Bl...
2,KQPW8lFf1y5BT2MxiSZ3QA,"""Western Motor Vehicle""",NaN,"""6025 N 27th Ave, Ste 1""",Phoenix,AZ,85017,33.524903,-112.115310,1.5,18,1,Departments of Motor Vehicles;Public Services ...
3,8DShNS-LuFqpEWIp0HxijA,"""Sports Authority""",NaN,"""5000 Arizona Mills Cr, Ste 435""",Tempe,AZ,85282,33.383147,-111.964725,3.0,9,0,Sporting Goods;Shopping
4,PfOCPjBrlQAnz__NXj9h_w,"""Brick House Tavern + Tap""",NaN,"""581 Howe Ave""",Cuyahoga Falls,OH,44221,41.119535,-81.475690,3.5,116,1,American (New);Nightlife;Bars;Sandwiches;Ameri...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
174562,ALV5R8NkZ1KGOZeuZl3u0A,"""Whitby Toyota""",NaN,"""1025 Dundas Street W""",Whitby,ON,L1P 1Z1,43.873460,-78.968033,4.0,4,1,Car Dealers;Automotive
174563,gRGalHVu6BcaUDIAGVW_xQ,"""Village Auto Body""",NaN,"""3957 Brecksville Rd""",Richfield,OH,44286,41.243385,-81.636212,5.0,3,1,Body Shops;Automotive
174564,XXvZBIHoJBU5d6-a-oyMWQ,"""AAM""",NaN,"""1600 W Broadway Rd, Ste 200""",Tempe,AZ,85282,33.407914,-111.965098,1.5,19,1,Home Services;Property Management;Real Estate
174565,lNpPGgM96nPIYM1shxciHg,"""Bronze Beauty Spray Tanning""",NaN,"""300 Camp Horne Rd, Ste 250""",Pittsburgh,PA,15202,40.517724,-80.091466,5.0,14,1,Spray Tanning;Tanning;Beauty & Spas
174566,viKaP26BcHU6cLx8sf4gKg,"""Phoenix Pharmacy""",NaN,"""1701 East Thomas Rd, Ste 105""",Phoenix,AZ,85016,33.479861,-112.044689,5.0,4,1,Drugstores;Shopping;Health & Medical

In [24]:
state = df.groupby('city').count()
print(state)

                business_id  name  neighborhood  address  state  postal_code  \
city
110 Las Vegas             1     1             1        1      1            1
AGINCOURT                 1     1             1        1      1            1
Aberdour                  1     1             0        1      1            1
Aberlady                  2     2             0        2      2            2
Ahwahtukee                1     1             0        1      1            1
...                     ...   ...           ...      ...    ...          ...
oakville                  1     1             0        1      1            1
peoria                    1     1             0        1      1            1
toronto                   5     5             3        5      5            5
Île des Soeurs            1     1             1        1      1            1
Île-des-Soeurs            1     1             1        1      1            1

                latitude  longitude  stars  review_count  is_open  categories
city
110 Las Vegas          1          1      1             1        1           1
AGINCOURT              1          1      1             1        1           1
Aberdour               1          1      1             1        1           1
Aberlady               2          2      2             2        2           2
Ahwahtukee             1          1      1             1        1           1
...                  ...        ...    ...           ...      ...         ...
oakville               1          1      1             1        1           1
peoria                 1          1      1             1        1           1
toronto                5          5      5             5        5           5
Île des Soeurs         1          1      1             1        1           1
Île-des-Soeurs         1          1      1             1        1           1

[1093 rows x 12 columns]

In [17]:
counts = df.sort_values('state')
print(counts)

                   business_id               name neighborhood  \
17311   -HpY7t06AtvasLfJJmY2ww          "Husmann"          NaN
99375   VR6vnB56lpH1Oa8rYIXpUw           "Go'Bua"          NaN
54867   WU_41ySU7HoF62lpTr633w       "Moss Sushi"          NaN
66663   39NX6v8cWKDnXIcVPFiFGQ          "Divinum"          NaN
141499  7MrVKrTj_cULIAF8Z3_P-A  "Ming Restaurant"          NaN
...                        ...                ...          ...
155168  5ho3ULJKSikoRJr-xpM4SQ          "Bramble"        Leith
93013   mmqSJyO2FNIlV18g4dMiWw    "The Hawes Inn"          NaN
28827   PtOViDy0tqoocic2DAgd6A        "Debenhams"     New Town
156754  nWz3HA2RvJDZzDNeonsA_w          "Nando's"     New Town
52815   SLqpLeF3gq6nnx6_JoE7-A       "5150 Wraps"          NaN

                                      address               city state  \
17311                          "Værftsgata 2"               Moss     1
99375                               "Buen 29"               Moss     1
54867                           "Storgata 14"               Moss     1
66663                            "Skoggata 2"               Moss     1
141499                  "Dronningens gate 27"               Moss     1
...                                       ...                ...   ...
155168                     "2 Crighton Place"          Edinburgh   XGL
93013                       "7 Newhalls Road"  South Queensferry   XGL
28827                    "109 Princes Street"          Edinburgh   XGL
156754         "Omni Centre, Greenside Place"          Edinburgh   ZET
52815   "250 Sunpac Ave, Ste 250, Ste A6 130"   Henderson Nevada   NaN

       postal_code   latitude   longitude  stars  review_count  is_open  \
17311         1511  59.433829   10.650990    4.5             3        1
99375         1528  59.422170   10.685297    4.5             3        1
54867         1531  59.435154   10.657473    4.0             5        1
66663         1530  59.436505   10.668057    3.5             6        1
141499        1530  59.435416   10.659771    3.0             4        1
...            ...        ...         ...    ...           ...      ...
155168     EH7 4NZ  55.962680   -3.178345    4.0             3        1
93013     EH30 9TA  55.989782   -3.385991    3.5            18        1
28827      EH2 3AA  55.951442   -3.202045    3.0            24        1
156754     EH1 3AA  55.956392   -3.186225    3.5             4        1
52815        89015  36.069521 -114.996331    5.0            12        1

                                               categories
17311   Caterers;Event Planning & Services;Traditional...
99375          Hot Dogs;Fast Food;Food Stands;Restaurants
54867                 Sushi Bars;Chinese;Thai;Restaurants
66663                           Italian;Pizza;Restaurants
141499                                        Restaurants
...                                                   ...
155168               Food;Convenience Stores;Coffee & Tea
93013                                 Nightlife;Bars;Pubs
28827                  Shopping;Department Stores;Fashion
156754               Restaurants;Chicken Wings;Portuguese
52815   Auto Customization;Vehicle Wraps;Automotive;Au...

[174567 rows x 13 columns]

In [19]:
fillna_drill = df.fillna